import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "display-lg": ["Geist", "sans-serif"],
        "telemetry-data-lg": ["JetBrains Mono", "monospace"],
        "label-code": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "telemetry-data-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "telemetry-data-lg": ["20px", { "lineHeight": "26px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "label-code": ["12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "telemetry-data-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.005em", "fontWeight": "400" }]
      },
      spacing: {
        "grid-margin-desktop": "2.5rem",
        "grid-margin-mobile": "1rem",
        "sm": "0.75rem",
        "xl": "2rem",
        "2xl": "3rem",
        "3xl": "4.5rem",
        "2xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "grid-margin-tablet": "1.5rem",
        "gutter-tablet": "1rem",
        "gutter-desktop": "1.5rem",
        "xs": "0.5rem",
        "lg": "1.5rem",
        "md": "1rem"
      },
      colors: {
        brand: {
          50: '#f0f7ff',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          glow: 'rgba(56, 189, 248, 0.15)',
        },
        ambient: {
          dark: '#0e0b0a',
          card: 'rgba(23, 20, 19, 0.72)',
          cardBorder: 'rgba(255, 255, 255, 0.08)',
        },
        amber: {
          350: '#fbbf24',
          450: '#f59e0b',
          550: '#d97706',
        },
        // MD3 Admin / Login theme
        "on-tertiary-container": "#004965",
        "primary-container": "#f59e0b",
        "secondary-container": "#00a2e6",
        "error-container": "#93000a",
        "on-surface": "#e9e1de",
        "on-tertiary": "#00354a",
        "on-primary-fixed": "#2a1700",
        "on-background": "#e9e1de",
        "outline-variant": "#534434",
        "secondary-fixed-dim": "#89ceff",
        "on-error-container": "#ffdad6",
        "secondary": "#89ceff",
        "primary-fixed": "#ffddb8",
        "on-primary": "#472a00",
        "tertiary-container": "#38bdf8",
        "outline": "#a08e7a",
        "inverse-primary": "#855300",
        "on-secondary": "#00344d",
        "tertiary": "#8ed5ff",
        "surface-container": "#231f1d",
        "error": "#ffb4ab",
        "surface-container-high": "#2d2928",
        "background": "#161311",
        "inverse-surface": "#e9e1de",
        "tertiary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#004c69",
        "on-tertiary-fixed": "#001e2c",
        "secondary-fixed": "#c9e6ff",
        "surface-variant": "#383432",
        "on-primary-container": "#613b00",
        "on-secondary-fixed-variant": "#004c6e",
        "surface": "#161311",
        "surface-container-highest": "#383432",
        "inverse-on-surface": "#342f2e",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-error": "#690005",
        "on-secondary-container": "#00344e",
        "surface-container-low": "#1e1b19",
        "on-secondary-fixed": "#001e2f",
        "on-surface-variant": "#d8c3ad",
        "surface-tint": "#ffb95f",
        "surface-container-lowest": "#110d0c",
        "surface-dim": "#161311",
        "primary": "#ffc174",
        "surface-bright": "#3d3837",
        "on-primary-fixed-variant": "#653e00"
      },
      boxShadow: {
        'glow': '0 0 50px -10px rgba(217, 119, 6, 0.18), 0 0 30px -12px rgba(56, 189, 248, 0.16)',
        'card-glass': '0 25px 50px -12px rgba(0, 0, 0, 0.75), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
        'pill-active': '0 0 15px rgba(56, 189, 248, 0.35)',
        'luminous': '0 0 25px -3px rgba(14, 165, 233, 0.65), 0 0 12px -1px rgba(56, 189, 248, 0.45), inset 0 1px 1.5px 0 rgba(255, 255, 255, 0.5)',
        'luminous-hover': '0 0 38px 0px rgba(14, 165, 233, 0.85), 0 0 18px 2px rgba(56, 189, 248, 0.6), inset 0 1px 2px 0 rgba(255, 255, 255, 0.8)',
      },
      animation: {
        'shimmer-slide': 'shimmerSlide 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'gleam-slide': 'gleamSlide 3.2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pulse-subtle': 'subtlePulse 2.8s ease-in-out infinite',
        'ambient-drift': 'ambientDrift 14s ease-in-out infinite alternate',
        'aurora-spin': 'auroraRotate 6s linear infinite',
        'badge-float': 'badgeFloat 2.4s ease-in-out infinite alternate',
        'icon-float': 'iconFloat 2s ease-in-out infinite alternate',
        'amber-breathe': 'amberBreathe 3s ease-in-out infinite alternate',
        'radar-wave-1': 'radarPing 2.5s cubic-bezier(0, 0, 0.2, 1) infinite',
        'radar-wave-2': 'radarPing 2.5s cubic-bezier(0, 0, 0.2, 1) 1.25s infinite',
        'logo-shimmer': 'logoShimmer 3s ease-in-out infinite',
        'gradient-pan': 'gradientPan 6s linear infinite',
        'gradient-flow': 'gradientFlow 3s linear infinite',
      },
      keyframes: {
        shimmerSlide: {
          '0%': { transform: 'translateX(-150%) skewX(-20deg)' },
          '40%, 100%': { transform: 'translateX(260%) skewX(-20deg)' },
        },
        gleamSlide: {
          '0%': { transform: 'translateX(-150%) skewX(-20deg)' },
          '40%, 100%': { transform: 'translateX(250%) skewX(-20deg)' },
        },
        subtlePulse: {
          '0%, 100%': { opacity: '0.8', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.06)' },
        },
        ambientDrift: {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '50%': { transform: 'translate(25px, -30px) scale(1.08)' },
          '100%': { transform: 'translate(-20px, 20px) scale(0.96)' },
        },
        auroraRotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        badgeFloat: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-2px)' },
        },
        iconFloat: {
          '0%': { transform: 'translateX(0) scale(1)' },
          '100%': { transform: 'translateX(2px) scale(1.1)' },
        },
        amberBreathe: {
          '0%': { boxShadow: '0 0 0 0 rgba(245, 158, 11, 0.2)', borderColor: 'rgba(245, 158, 11, 0.3)' },
          '100%': { boxShadow: '0 0 16px 2px rgba(245, 158, 11, 0.45)', borderColor: 'rgba(251, 191, 36, 0.65)' },
        },
        radarPing: {
          '0%': { transform: 'scale(0.95)', opacity: '0.8' },
          '70%, 100%': { transform: 'scale(2.1)', opacity: '0' },
        },
        logoShimmer: {
          '0%, 100%': { opacity: '0.9' },
          '50%': { opacity: '1' }
        },
        gradientPan: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        gradientFlow: {
          '0%': { backgroundPosition: '200% center' },
          '100%': { backgroundPosition: '-200% center' },
        }
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
export default config;
