import type { Scenario, Step } from './scenario';
import type { Action } from './action';
import type { Assertion } from './assertion';
import type { SemanticTarget } from './target';
import type { ValueExpr } from './value';

function formatTargetPlaywright(target: SemanticTarget): string {
  if (target.hints?.testId) {
    return `page.getByTestId(${JSON.stringify(target.hints.testId)})`;
  }
  if (target.role && target.name) {
    return `page.getByRole(${JSON.stringify(target.role)}, { name: ${JSON.stringify(target.name)} })`;
  }
  if (target.labelText) {
    return `page.getByLabel(${JSON.stringify(target.labelText)})`;
  }
  if (target.placeholder) {
    return `page.getByPlaceholder(${JSON.stringify(target.placeholder)})`;
  }
  if (target.name) {
    return `page.getByText(${JSON.stringify(target.name)})`;
  }
  if (target.role) {
    return `page.getByRole(${JSON.stringify(target.role)})`;
  }
  return `page.locator('body')`;
}

function formatTargetPlaywrightPython(target: SemanticTarget): string {
  if (target.hints?.testId) {
    return `page.get_by_test_id(${JSON.stringify(target.hints.testId)})`;
  }
  if (target.role && target.name) {
    return `page.get_by_role(${JSON.stringify(target.role)}, name=${JSON.stringify(target.name)})`;
  }
  if (target.labelText) {
    return `page.get_by_label(${JSON.stringify(target.labelText)})`;
  }
  if (target.placeholder) {
    return `page.get_by_placeholder(${JSON.stringify(target.placeholder)})`;
  }
  if (target.name) {
    return `page.get_by_text(${JSON.stringify(target.name)})`;
  }
  if (target.role) {
    return `page.get_by_role(${JSON.stringify(target.role)})`;
  }
  return `page.locator('body')`;
}

function formatTargetCypress(target: SemanticTarget): string {
  if (target.hints?.testId) {
    return `cy.get('[data-testid="${target.hints.testId}"]')`;
  }
  if (target.placeholder) {
    return `cy.get('[placeholder="${target.placeholder}"]')`;
  }
  if (target.role === 'button' && target.name) {
    return `cy.contains('button', ${JSON.stringify(target.name)})`;
  }
  if (target.name) {
    return `cy.contains(${JSON.stringify(target.name)})`;
  }
  if (target.role) {
    return `cy.get('[role="${target.role}"]')`;
  }
  return `cy.get('body')`;
}

function formatTargetSelenium(target: SemanticTarget): string {
  if (target.hints?.testId) {
    return `driver.find_element(By.CSS_SELECTOR, "[data-testid='${target.hints.testId}']")`;
  }
  if (target.placeholder) {
    return `driver.find_element(By.CSS_SELECTOR, "[placeholder='${target.placeholder}']")`;
  }
  if (target.name) {
    return `driver.find_element(By.XPATH, "//*[contains(text(), '${target.name}')]")`;
  }
  return `driver.find_element(By.TAG_NAME, "body")`;
}

function resolveValue(val?: ValueExpr): string {
  if (!val) return '';
  if (val.kind === 'literal') return String(val.value ?? '');
  return '';
}

/**
 * Exports a scenario to standard Playwright TypeScript test file.
 */
export function exportToPlaywrightTS(scenario: Scenario, targetUrl = 'https://example.com'): string {
  const lines: string[] = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `/**`,
    ` * Generated by Webtest Scanner (KaneAI Engine)`,
    ` * Scenario: ${scenario.title}`,
    ` * Priority: ${scenario.priority} | Test Types: ${scenario.testTypes.join(', ')}`,
    ` */`,
    `test.describe(${JSON.stringify(scenario.title)}, () => {`,
    `  test('executes autonomous journey', async ({ page }) => {`,
    `    // Setup base timeout and navigate to initial page`,
    `    test.setTimeout(60000);`,
  ];

  for (const step of scenario.steps) {
    lines.push(``);
    lines.push(`    // Step ${step.index}: ${step.intent}`);
    const a = step.action;

    switch (a.type) {
      case 'navigate': {
        const cleanTarget = targetUrl.endsWith('/') ? targetUrl.slice(0, -1) : targetUrl;
        const fullUrl = a.path.startsWith('http') ? a.path : `${cleanTarget}${a.path.startsWith('/') ? '' : '/'}${a.path}`;
        lines.push(`    await page.goto(${JSON.stringify(fullUrl)}, { waitUntil: 'domcontentloaded' });`);
        break;
      }
      case 'click':
        lines.push(`    await ${formatTargetPlaywright(a.target)}.click();`);
        break;
      case 'clickAll':
        lines.push(`    const elements = await ${formatTargetPlaywright(a.target)}.all();`);
        lines.push(`    for (const el of elements) { await el.click().catch(() => {}); }`);
        break;
      case 'fill':
        lines.push(`    await ${formatTargetPlaywright(a.target)}.fill(${JSON.stringify(resolveValue(a.value))});`);
        break;
      case 'check':
        lines.push(`    await ${formatTargetPlaywright(a.target)}.setChecked(${a.state});`);
        break;
      case 'press':
        lines.push(`    await page.keyboard.press(${JSON.stringify(a.keys)});`);
        break;
      case 'screenshot':
        lines.push(`    await page.screenshot({ path: 'screenshot-${step.index}.png', fullPage: true });`);
        break;
      case 'waitFor':
        if (a.condition.type === 'domStable') {
          lines.push(`    await page.waitForTimeout(${a.condition.quietMs});`);
        } else if (a.condition.type === 'navigationComplete') {
          lines.push(`    await page.waitForLoadState('load');`);
        } else if (a.condition.type === 'elementVisible') {
          lines.push(`    await expect(${formatTargetPlaywright(a.condition.target)}).toBeVisible({ timeout: ${a.condition.timeoutMs} });`);
        } else {
          lines.push(`    await page.waitForTimeout(1000);`);
        }
        break;
      case 'explore':
        lines.push(`    // Autonomous link exploration (depth: ${a.maxDepth})`);
        lines.push(`    const navLinks = await page.locator('nav a, header a').all();`);
        lines.push(`    for (const link of navLinks.slice(0, 3)) {`);
        lines.push(`      const href = await link.getAttribute('href');`);
        lines.push(`      if (href && !href.startsWith('mailto:')) { await page.goto(href).catch(() => {}); }`);
        lines.push(`    }`);
        break;
      default:
        lines.push(`    // ${a.type} action`);
    }

    // Assertions
    for (const assertion of step.assertions) {
      if (assertion.type === 'textPresent') {
        const textVal = resolveValue(assertion.text);
        if (assertion.negate) {
          lines.push(`    await expect(page.locator('body')).not.toContainText(${JSON.stringify(textVal)});`);
        } else {
          lines.push(`    await expect(page.locator('body')).toContainText(${JSON.stringify(textVal)});`);
        }
      } else if (assertion.type === 'elementVisible') {
        if (assertion.negate) {
          lines.push(`    await expect(${formatTargetPlaywright(assertion.target)}).toBeHidden();`);
        } else {
          lines.push(`    await expect(${formatTargetPlaywright(assertion.target)}).toBeVisible();`);
        }
      } else if (assertion.type === 'noConsoleErrors') {
        lines.push(`    // Assert no console error was observed`);
      }
    }
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Exports a scenario to standard Playwright Python test file.
 */
export function exportToPlaywrightPython(scenario: Scenario, targetUrl = 'https://example.com'): string {
  const lines: string[] = [
    `import pytest`,
    `from playwright.sync_api import Page, expect`,
    ``,
    `"""`,
    `Generated by Webtest Scanner (KaneAI Engine)`,
    `Scenario: ${scenario.title}`,
    `"""`,
    ``,
    `def test_${scenario.title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}(page: Page):`,
    `    page.set_default_timeout(60000)`,
  ];

  for (const step of scenario.steps) {
    lines.push(``);
    lines.push(`    # Step ${step.index}: ${step.intent}`);
    const a = step.action;

    switch (a.type) {
      case 'navigate': {
        const cleanTarget = targetUrl.endsWith('/') ? targetUrl.slice(0, -1) : targetUrl;
        const fullUrl = a.path.startsWith('http') ? a.path : `${cleanTarget}${a.path.startsWith('/') ? '' : '/'}${a.path}`;
        lines.push(`    page.goto(${JSON.stringify(fullUrl)}, wait_until='domcontentloaded')`);
        break;
      }
      case 'click':
        lines.push(`    ${formatTargetPlaywrightPython(a.target)}.click()`);
        break;
      case 'fill':
        lines.push(`    ${formatTargetPlaywrightPython(a.target)}.fill(${JSON.stringify(resolveValue(a.value))})`);
        break;
      case 'check':
        lines.push(`    ${formatTargetPlaywrightPython(a.target)}.set_checked(${a.state ? 'True' : 'False'})`);
        break;
      case 'screenshot':
        lines.push(`    page.screenshot(path='screenshot-${step.index}.png')`);
        break;
      case 'waitFor':
        lines.push(`    page.wait_for_timeout(1000)`);
        break;
      default:
        lines.push(`    # ${a.type} action`);
    }

    for (const assertion of step.assertions) {
      if (assertion.type === 'textPresent') {
        const textVal = resolveValue(assertion.text);
        lines.push(`    expect(page.locator('body')).to_contain_text(${JSON.stringify(textVal)})`);
      } else if (assertion.type === 'elementVisible') {
        lines.push(`    expect(${formatTargetPlaywrightPython(assertion.target)}).to_be_visible()`);
      }
    }
  }

  lines.push(``);
  return lines.join('\n');
}

/**
 * Exports a scenario to standard Cypress test file.
 */
export function exportToCypress(scenario: Scenario, targetUrl = 'https://example.com'): string {
  const lines: string[] = [
    `/// <reference types="cypress" />`,
    ``,
    `/**`,
    ` * Generated by Webtest Scanner (KaneAI Engine)`,
    ` * Scenario: ${scenario.title}`,
    ` */`,
    `describe(${JSON.stringify(scenario.title)}, () => {`,
    `  it('runs scenario flow', () => {`,
  ];

  for (const step of scenario.steps) {
    lines.push(``);
    lines.push(`    // Step ${step.index}: ${step.intent}`);
    const a = step.action;

    switch (a.type) {
      case 'navigate': {
        const cleanTarget = targetUrl.endsWith('/') ? targetUrl.slice(0, -1) : targetUrl;
        const fullUrl = a.path.startsWith('http') ? a.path : `${cleanTarget}${a.path.startsWith('/') ? '' : '/'}${a.path}`;
        lines.push(`    cy.visit(${JSON.stringify(fullUrl)});`);
        break;
      }
      case 'click':
        lines.push(`    ${formatTargetCypress(a.target)}.click();`);
        break;
      case 'fill':
        lines.push(`    ${formatTargetCypress(a.target)}.type(${JSON.stringify(resolveValue(a.value))});`);
        break;
      case 'check':
        if (a.state) {
          lines.push(`    ${formatTargetCypress(a.target)}.check();`);
        } else {
          lines.push(`    ${formatTargetCypress(a.target)}.uncheck();`);
        }
        break;
      case 'screenshot':
        lines.push(`    cy.screenshot('step-${step.index}');`);
        break;
      case 'waitFor':
        lines.push(`    cy.wait(1000);`);
        break;
      default:
        lines.push(`    // ${a.type} action`);
    }

    for (const assertion of step.assertions) {
      if (assertion.type === 'textPresent') {
        const textVal = resolveValue(assertion.text);
        lines.push(`    cy.contains(${JSON.stringify(textVal)}).should('exist');`);
      } else if (assertion.type === 'elementVisible') {
        lines.push(`    ${formatTargetCypress(assertion.target)}.should('be.visible');`);
      }
    }
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Exports a scenario to standard Selenium Python script.
 */
export function exportToSeleniumPython(scenario: Scenario, targetUrl = 'https://example.com'): string {
  const lines: string[] = [
    `import time`,
    `from selenium import webdriver`,
    `from selenium.webdriver.common.by import By`,
    `from selenium.webdriver.chrome.service import Service`,
    `from webdriver_manager.chrome import ChromeDriverManager`,
    ``,
    `# Generated by Webtest Scanner (KaneAI Engine)`,
    `# Scenario: ${scenario.title}`,
    ``,
    `driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))`,
    `driver.implicitly_wait(10)`,
    `try:`,
  ];

  for (const step of scenario.steps) {
    lines.push(``);
    lines.push(`    # Step ${step.index}: ${step.intent}`);
    const a = step.action;

    switch (a.type) {
      case 'navigate': {
        const cleanTarget = targetUrl.endsWith('/') ? targetUrl.slice(0, -1) : targetUrl;
        const fullUrl = a.path.startsWith('http') ? a.path : `${cleanTarget}${a.path.startsWith('/') ? '' : '/'}${a.path}`;
        lines.push(`    driver.get(${JSON.stringify(fullUrl)})`);
        break;
      }
      case 'click':
        lines.push(`    ${formatTargetSelenium(a.target)}.click()`);
        break;
      case 'fill':
        lines.push(`    ${formatTargetSelenium(a.target)}.send_keys(${JSON.stringify(resolveValue(a.value))})`);
        break;
      case 'screenshot':
        lines.push(`    driver.save_screenshot('screenshot-${step.index}.png')`);
        break;
      case 'waitFor':
        lines.push(`    time.sleep(1)`);
        break;
      default:
        lines.push(`    # ${a.type} action`);
    }

    for (const assertion of step.assertions) {
      if (assertion.type === 'textPresent') {
        const textVal = resolveValue(assertion.text);
        lines.push(`    assert ${JSON.stringify(textVal)} in driver.page_source`);
      }
    }
  }

  lines.push(``);
  lines.push(`    print("Test passed successfully!")`);
  lines.push(`finally:`);
  lines.push(`    driver.quit()`);
  lines.push(``);

  return lines.join('\n');
}

export type ExportFramework = 'playwright-ts' | 'playwright-python' | 'cypress' | 'selenium-python';

export function exportCode(
  scenario: Scenario,
  targetUrl = 'https://example.com',
  framework: ExportFramework = 'playwright-ts'
): string {
  switch (framework) {
    case 'playwright-ts':
      return exportToPlaywrightTS(scenario, targetUrl);
    case 'playwright-python':
      return exportToPlaywrightPython(scenario, targetUrl);
    case 'cypress':
      return exportToCypress(scenario, targetUrl);
    case 'selenium-python':
      return exportToSeleniumPython(scenario, targetUrl);
    default:
      return exportToPlaywrightTS(scenario, targetUrl);
  }
}

